stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy_to_server:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
  script:
    - ssh arzhannikov@$109.205.56.59 "rm -rf /var/www/school-frontend/*"
    - rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" dist/ arzhannikov@$109.205.56.59:/var/www/school-frontend
  only:
    - master
