name: Build and Deploy School Frontend

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Show build files
        run: ls -la dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: school-frontend-build
          path: dist/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: school-frontend-build
          path: dist/

      - name: Debug environment variables
        run: |
          echo "Checking environment variables..."
          echo "SERVER_IP: ${{ secrets.SERVER_IP }}"
          echo "SSH_USER: ${{ secrets.SSH_USER }}"

      - name: Check if SSH key exists
        run: |
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "ERROR: SSH_PRIVATE_KEY is missing!"
            exit 1
          else
            echo "SSH_PRIVATE_KEY is set."
          fi

      - name: Setup SSH connection
        run: |
          echo "Setting up SSH..."
          mkdir -p ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Verify SSH private key
        run: |
          echo "Checking SSH private key..."
          cat ~/.ssh/id_rsa
          ls -l ~/.ssh

      - name: Test SSH connection
        run: |
          echo "Testing SSH connection..."
          ssh -v -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "echo 'SSH connection successful!'"

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/school-frontend"
          strip_components: 1
