name: Build and Deploy React App

on:
  push:
    branches: [ master ]  # Триггер на пуш в ветку main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Клонирует репозиторий

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Версия Node.js

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Создает папку dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: dist/  # Артефакт для деплоя

  deploy:
    needs: build  # Ждет завершения сборки
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: react-build

      - name: Deploy to server via SSH
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}  # IP сервера из Secrets
          username: ${{ secrets.SSH_USER }}  # Логин для SSH
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Приватный ключ
          source: "dist/*"  # Что копировать
          target: "/var/www/school-frontend"  # Куда копировать
