name: Optimized School Frontend Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: school-build
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: school-build
          path: dist/

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy and Verify
        run: |
          tar -czf deploy.tar.gz -C dist .
          scp -i ~/.ssh/id_rsa deploy.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/tmp/
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} \
            "mkdir -p /var/www/school-frontend/dist && \
             tar -xzf /tmp/deploy.tar.gz -C /var/www/school-frontend/dist && \
             chown -R arzhannikov:arzhannikov /var/www/school-frontend/dist && \
             rm /tmp/deploy.tar.gz && \
             ls -la /var/www/school-frontend/dist"
          rm deploy.tar.gz
