name: Build and Deploy School Frontend

on:
  push:
    branches: [ master ]  # Используем ветку master вместо main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Папка dist/ будет создана после сборки

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: school-frontend-build
          path: dist/
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: school-frontend-build

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/school-frontend"  # Путь на сервере
          strip-components: 1  # Игнорируем папку dist/ при копировании
